par(mfrow=c(1,5))
matplot(Samples.theta[,1], type = 'l',xlab='MCMC iteration','ylab' = 'theta_1')
axis(side=1, at=axTicks(1), labels=formatC(axTicks(1), format="d", big.mark=','))
matplot(Samples.theta[,2], type = 'l',xlab='MCMC iteration','ylab' = 'theta_2')
axis(side=1, at=axTicks(1), labels=formatC(axTicks(1), format="d", big.mark=','))
matplot(Samples.theta[,3], type = 'l',xlab='MCMC iteration','ylab' = 'theta_3')
axis(side=1, at=axTicks(1), labels=formatC(axTicks(1), format="d", big.mark=','))
matplot(Samples.theta[,4], type = 'l',xlab='MCMC iteration','ylab' = 'theta_4')
axis(side=1, at=axTicks(1), labels=formatC(axTicks(1), format="d", big.mark=','))
matplot(Samples.theta[,5], type = 'l',xlab='MCMC iteration','ylab' = 'theta_5')
axis(side=1, at=axTicks(1), labels=formatC(axTicks(1), format="d", big.mark=','))